#woo
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git for commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Clone HF Space repo
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          rm -rf hf-space
          git clone https://AlbertoRoca96-web:${HF_TOKEN}@huggingface.co/spaces/AlbertoRoca96-web/pointkedex hf-space

      - name: Ensure jq is available
        run: |
          if ! command -v jq >/dev/null; then
            sudo apt-get update
            sudo apt-get install -y jq
          fi

      - name: Download usage_data.json and .h5 from release (shell-only)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          OWNER="AlbertoRoca96"
          REPO="pointkedex"
          TAG="alroca"

          # Fetch the release JSON by tag
          release_json=$(curl -sSL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            "https://api.github.com/repos/${OWNER}/${REPO}/releases/tags/${TAG}")

          usage_url=$(printf '%s' "$release_json" | jq -r '.assets[] | select(.name=="usage_data.json") | .browser_download_url')
          h5_url=$(printf '%s' "$release_json" | jq -r '.assets[] | select(.name=="pokedex_resnet50.h5") | .browser_download_url')

          if [[ -z "$usage_url" || "$usage_url" == "null" ]]; then
            echo "❌ usage_data.json asset not found in release ${TAG}"
            exit 1
          fi
          if [[ -z "$h5_url" || "$h5_url" == "null" ]]; then
            echo "❌ pokedex_resnet50.h5 asset not found in release ${TAG}"
            exit 1
          fi

          # Download the assets
          curl -L -H "Authorization: Bearer ${GITHUB_TOKEN}" -o usage_data.json "$usage_url"
          curl -L -H "Authorization: Bearer ${GITHUB_TOKEN}" -o pokedex_resnet50.h5 "$h5_url"

      - name: Sync files to HF Space
        run: |
          rsync -a --delete \
            Dockerfile predict_server.py index.html app.js styles.css \
            config.js flavor_text.json class_indices.json pokedex_data.json \
            usage_data.json service-worker.js manifest.webmanifest \
            hf-space/

      - name: Commit & push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd hf-space
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to push."
          else
            git commit -m "Sync app files from GitHub main"
            git push
          fi
