name: Deploy to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Clone HF Space repo
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://AlbertoRoca96-web:${HF_TOKEN}@huggingface.co/spaces/AlbertoRoca96-web/pointkedex hf-space

      - name: Enable Git LFS in HF Space and track large assets
        run: |
          cd hf-space
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install
          git lfs track "usage_data.json" "pokedex_resnet50.h5"
          git add .gitattributes
          if ! git diff --cached --quiet; then
            git commit -m "Enable Git LFS for large assets"
          fi
          cd ..

      - name: Fetch release assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download alroca --repo AlbertoRoca96/pointkedex -p usage_data.json -p pokedex_resnet50.h5 || \
          gh release download --repo AlbertoRoca96/pointkedex -p usage_data.json -p pokedex_resnet50.h5

      - name: Sync files
        run: |
          rsync -a --delete \
            Dockerfile predict_server.py index.html app.js styles.css \
            config.js flavor_text.json class_indices.json pokedex_data.json \
            usage_data.json service-worker.js manifest.webmanifest pokedex_resnet50.h5 \
            hf-space/

      - name: Commit & push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd hf-space
          git add -A
          git commit -m "Sync app files from GitHub main"
          git push
          fi

