on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Clone HF Space repo
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://AlbertoRoca96-web:${HF_TOKEN}@huggingface.co/spaces/AlbertoRoca96-web/pointkedex hf-space

      - name: Ensure tools for release download
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Download usage_data.json from GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          OWNER="AlbertoRoca96"
          REPO="pointkedex"
          TAG="alroca"  # release tag you have
          ASSET_NAME="usage_data.json"

          # Fetch release metadata
          release_json=$(curl -s -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            "https://api.github.com/repos/${OWNER}/${REPO}/releases/tags/${TAG}")

          asset_id=$(echo "$release_json" | jq -r '.assets[] | select(.name=="'"${ASSET_NAME}"'") | .id')

          if [ -z "$asset_id" ] || [ "$asset_id" = "null" ]; then
            echo "❌ usage_data.json asset not found in release ${TAG}"
            exit 1
          fi

          # Download the raw asset binary
          curl -L \
            -H "Accept: application/octet-stream" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            "https://api.github.com/repos/${OWNER}/${REPO}/releases/assets/${asset_id}" \
            -o usage_data.json

      # ── copy every file the app needs ─────────────────────────────
      - name: Sync files
        run: |
          rsync -a --delete \
            Dockerfile predict_server.py index.html app.js styles.css \
            config.js flavor_text.json class_indices.json pokedex_data.json \
            usage_data.json service-worker.js manifest.webmanifest \
            hf-space/

      - name: Commit & push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd hf-space
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to push."
          else
            git commit -m "Sync app files from GitHub main"
            git push
          fi